function dr_check_w = dr_check_w_of_rz(r,z,l,rho_l_minus2,...
                                       rho_l_minus4, ...
                                       c_theta,s_theta)

dr_check_w = + l          *rho_l_minus2*s_theta ...
             + l*(l-2)*r*r*rho_l_minus4*s_theta ...
             + l* l   *r*z*rho_l_minus4*c_theta ...
             + l*(l-2)*r*z*rho_l_minus4*c_theta ...
             - l* l   *z*z*rho_l_minus4*s_theta;