function drphi_check_u = drphi_check_u_of_rz(r,z,l,rho_l_minus2,...
                                             rho_l_minus4, ...
                                             c_theta,s_theta)

drphi_check_u = - l*l*(l-2)*r*z*rho_l_minus4*c_theta ...
                + l*l* l   *z*z*rho_l_minus4*s_theta ...
                - l*l          *rho_l_minus2*s_theta ...
                - l*l*(l-2)*r*r*rho_l_minus4*s_theta ...
                - l*l* l   *r*z*rho_l_minus4*c_theta;