function diff_lambda_eig_u ...
          = dlambdaeig_check_u_of_rzl(r,z,l, ...
                                      rho_l_minus2_pp, ...
                                      c_theta_pp,s_theta_pp, ...
                                      ln_rho2_pp,phi_pp)
   
diff_lambda_eig_u =   ...
    -     z*rho_l_minus2_pp           *s_theta_pp ...
    -.5*l*z*rho_l_minus2_pp*ln_rho2_pp*s_theta_pp ...
    -   l*z*rho_l_minus2_pp           *c_theta_pp*phi_pp ...
    +     r*rho_l_minus2_pp           *c_theta_pp ...
    +.5*l*r*rho_l_minus2_pp*ln_rho2_pp*c_theta_pp ...
    -   l*r*rho_l_minus2_pp           *s_theta_pp*phi_pp;