function dr_check_u = dr_check_u_of_rz(r,z,l,rho_l_minus2,...
                                       rho_l_minus4, ...
                                       c_theta,s_theta)

dr_check_u = - l*(l-2)*r*z*rho_l_minus4*s_theta ...
             - l* l   *z*z*rho_l_minus4*c_theta ...
             + l          *rho_l_minus2*c_theta ...
             + l*(l-2)*r*r*rho_l_minus4*c_theta ...
             - l* l   *r*z*rho_l_minus4*s_theta;