function diff_zlambda_eig_w ...
          = dzlambdaeig_check_w_of_rzl(r,z,l, ...
                                      rho_l_minus2_pp, ...
                                      rho_l_minus4_pp, ...
                                      c_theta_pp,s_theta_pp, ...
                                      ln_rho2_pp,phi_pp)                                
diff_zlambda_eig_w =   ...
      2  *(l-1)*r*z*rho_l_minus4_pp           *s_theta_pp ...
    +.5*l*(l-2)*r*z*rho_l_minus4_pp*ln_rho2_pp*s_theta_pp ...
    +   l*(l-2)*r*z*rho_l_minus4_pp           *c_theta_pp*phi_pp ...
    - 2*l      *r*r*rho_l_minus4_pp           *c_theta_pp ...
    -.5*l* l   *r*r*rho_l_minus4_pp*ln_rho2_pp*c_theta_pp ...
    +   l* l   *r*r*rho_l_minus4_pp           *s_theta_pp*phi_pp ...
    +               rho_l_minus2_pp           *c_theta_pp ...
    +.5*l          *rho_l_minus2_pp*ln_rho2_pp*c_theta_pp ...
    -   l          *rho_l_minus2_pp           *s_theta_pp*phi_pp ...
    + 2  *(l-1)*z*z*rho_l_minus4_pp           *c_theta_pp ...
    +.5*l*(l-2)*z*z*rho_l_minus4_pp*ln_rho2_pp*c_theta_pp ...
    -   l*(l-2)*z*z*rho_l_minus4_pp           *s_theta_pp*phi_pp ...
    + 2*l      *r*z*rho_l_minus4_pp           *s_theta_pp ...
    +.5*l* l   *r*z*rho_l_minus4_pp*ln_rho2_pp*s_theta_pp ...
    +   l* l   *r*z*rho_l_minus4_pp           *c_theta_pp*phi_pp;