function dzphi_check_w = dzphi_check_w_of_rz(r,z,l,rho_l_minus2,...
                                             rho_l_minus4, ...
                                             c_theta,s_theta)

dzphi_check_w =   l*l*(l-2)*r*z*rho_l_minus4*c_theta ...
                + l*l* l   *r*r*rho_l_minus4*s_theta ...
                - l*l          *rho_l_minus2*s_theta ...
                - l*l*(l-2)*z*z*rho_l_minus4*s_theta ...
                + l*l* l   *r*z*rho_l_minus4*c_theta;