close all
clear
clc

change = 1.6; %This should be slighly greater than pi/2

hs = 0;
save('hs.mat','hs')

%time step
delta_t = 1E-2;
save('delta_t.mat','delta_t')
%Number of time steps
n_steps = 100;

ratio_n = 2;
a_n = 2*(1+2*ratio_n)/(3*(1+ratio_n));
a_n_minus1 = 2*(1+ratio_n)/3;
a_n_minus2 = 2*ratio_n^2/(3*(1+ratio_n));

%convergence criteria
tol_R = 1E-6;
tol_err = 1E-4;

%Numerical derivative parameter
del_h = 0.0001; %Incremental factor to estimante derivatives 
%with respect to first spine length

%Dimensionless numbers for bulk
load('Re.mat');%Re = U_dim*L_dim/nu_dim; %Reynolds number
load('Ca.mat')%Ca = rho_dim*nu_dim*U_dim/sigma_1e_dim; %Capillary number
load('St.mat')%St = g_dim*L_dim^2/(nu_dim*U_dim); %Stokes number

%Dimensionless numbers for the liquid-gas IFM
load('Bg.mat','Bg')
load('Eg.mat','Eg')
load('Cg.mat','Cg')
load('Dg.mat','Dg')
load('Lg.mat','Lg')
load('Tg.mat','Tg')

%Dimensionless numbers for liquid-gas IFM
load('Be.mat','Be')
load('Es.mat','Es')
load('Cs.mat','Cs')
load('Ds.mat','Ds')
load('Ls.mat','Ls')
load('Ts.mat','Ts')

%Contact line dimensionless numbers
load('So.mat','So')

%Mesh properties
load('l.mat')
load('n_nodes_const_per_spine.mat')
load('n_el_sing.mat')
load('press_lim_node_solid.mat')
load('press_lim_node_gas.mat')
load('n_spines.mat')
load('n_spines_incr.mat')
load('n_spines_near.mat')
load('n_spines_far.mat')
spine_nums_near = 1:n_spines_near;
spine_nums_far = n_spines_near:n_spines;
load('spine_feet_locator.mat')
load('alpha_s.mat')
load('n_v.mat')
load('n_v_near.mat')
load('n_v_far.mat')
load('n_v_start_far.mat')
load('n_el.mat')
load('n_el_near.mat')
load('n_Mr_near.mat')
load('Mr_nodes_near.mat')
load('n_Mz_near.mat')
load('Mz_nodes_near.mat')
load('n_C_near.mat')
load('C_nodes_near.mat')
load('n_K_near.mat')
load('K_nodes_near.mat')
load('n_I_near.mat')
load('I_nodes_near.mat')
load('n_Mr_far.mat')
load('Mr_nodes_far.mat')
load('n_Mz_far.mat')
load('Mz_nodes_far.mat')
load('n_C_far.mat')
load('C_nodes_far.mat')
load('n_K_far.mat')
load('K_nodes_far.mat')
load('n_I_far.mat')
load('I_nodes_far.mat')
load('n_u_k_near.mat')
load('unodes_nums_k_near.mat')
load('n_u_uk_near.mat')
load('unodes_nums_uk_near.mat')
load('n_u_k_far.mat')
load('unodes_nums_k_far.mat')
load('n_u_uk_far.mat')
load('unodes_nums_uk_far.mat')
load('n_w_k_near.mat')
load('wnodes_nums_k_near.mat')
load('n_w_uk_near.mat')
load('wnodes_nums_uk_near.mat')
load('n_w_k_far.mat')
load('wnodes_nums_k_far.mat')
load('n_w_uk_far.mat')
load('wnodes_nums_uk_far.mat')
load('pNodes_rz.mat')
load('n_p.mat')
load('n_p_near.mat')
load('n_p_far.mat')
load('n_p_start_far.mat')
load('n_p_k_near.mat')
load('pnodes_nums_k_near.mat')
load('n_p_uk_near.mat')
load('pnodes_nums_uk_near.mat')
load('n_p_k_far.mat')
load('pnodes_nums_k_far.mat')
load('n_p_uk_far.mat')
load('pnodes_nums_uk_far.mat')
load('n_lambda2_uk.mat','n_lambda2_uk')
load('lp.mat')
load('spine_feet_nodes.mat')
load('spine_tip_nodes.mat')
load('contact_line.mat')
load('apex.mat')
load('n1_el.mat')
load('n1_el_near.mat')
load('l_1.mat')
load('l1_1.mat')
load('phi1_lG.mat')
load('phi1_xi_lG.mat')
load('n2_el.mat')
load('n2_el_near.mat')
load('l_2.mat')
load('l2_2.mat')
load('n3_el.mat')
load('l_3.mat')
load('l3_3.mat')
load('n4_el.mat')
load('l_4.mat')
load('l4_4.mat')
load('n5_el.mat')
load('l_5.mat')
load('l5_5.mat')
load('S.mat')
load('S_1.mat')
load('S_2.mat')
load('S_3.mat')
load('S_4.mat')
load('S_5.mat')
load('el_s_loc_nodes.mat')
load('el1_s_loc_nodes.mat')
load('el2_s_loc_nodes.mat')
load('el3_s_loc_nodes.mat')
load('el4_s_loc_nodes.mat')
load('el5_s_loc_nodes.mat')
load('alpha_1.mat')
load('alpha_2.mat')
load('alpha_3.mat')
load('alpha_4.mat')
load('alpha_5.mat')
load('n_v_pre_start_far.mat','n_v_pre_start_far')
load('n_p_pre_start_far.mat','n_p_pre_start_far')
load('n_v_sep.mat','n_v_sep')
load('n_p_sep.mat','n_p_sep')
load('n_lambda2_uk_near.mat','n_lambda2_uk_near')
load('n_lambda2_uk_far.mat','n_lambda2_uk_far')
load('sep_nodes.mat','sep_nodes')
load('n_us2_uk_near.mat','n_us2_uk_near')
load('n_ws2_uk_near.mat','n_ws2_uk_near')
load('n_rhos2_uk_near.mat','n_rhos2_uk_near')
load('n_sigma2_uk_near.mat','n_sigma2_uk_near')
load('n_us1_uk_near.mat','n_us1_uk_near')
load('n_ws1_uk_near.mat','n_ws1_uk_near')
load('n_rhos1_uk_near.mat','n_rhos1_uk_near')
load('n_sigma1_uk_near.mat','n_sigma1_uk_near')
load('n_us2_uk_far.mat','n_us2_uk_far')
load('n_ws2_uk_far.mat','n_ws2_uk_far')
load('n_rhos2_uk_far.mat','n_rhos2_uk_far')
load('n_sigma2_uk_far.mat','n_sigma2_uk_far')
load('n_us1_uk_far.mat','n_us1_uk_far')
load('n_ws1_uk_far.mat','n_ws1_uk_far')
load('n_rhos1_uk_far.mat','n_rhos1_uk_far')
load('n_sigma1_uk_far.mat','n_sigma1_uk_far')
load('n_S2_near.mat','n_S2_near')
load('n_E2_near.mat','n_E2_near')
load('n_D2_near.mat','n_D2_near')
load('n_T2_near.mat','n_T2_near')
load('n_S1_near.mat','n_S1_near')
load('n_E1_near.mat','n_E1_near')
load('n_D1_near.mat','n_D1_near')
load('n_T1_near.mat','n_T1_near')
load('n_S2_far.mat','n_S2_far')
load('n_E2_far.mat','n_E2_far')
load('n_D2_far.mat','n_D2_far')
load('n_T2_far.mat','n_T2_far')
load('n_S1_far.mat','n_S1_far')
load('n_E1_far.mat','n_E1_far')
load('n_D1_far.mat','n_D1_far')
load('n_T1_far.mat','n_T1_far')
load('lambda2nodes_nums_uk_near.mat','lambda2nodes_nums_uk_near')
load('us2nodes_nums_uk_near.mat','us2nodes_nums_uk_near')
load('ws2nodes_nums_uk_near.mat','ws2nodes_nums_uk_near')
load('rhos2nodes_nums_uk_near.mat','rhos2nodes_nums_uk_near')
load('sigma2nodes_nums_uk_near.mat','sigma2nodes_nums_uk_near')
load('spine_nums_uk_near.mat','spine_nums_uk_near')
load('us1nodes_nums_uk_near.mat','us1nodes_nums_uk_near')
load('ws1nodes_nums_uk_near.mat','ws1nodes_nums_uk_near')
load('rhos1nodes_nums_uk_near.mat','rhos1nodes_nums_uk_near')
load('sigma1nodes_nums_uk_near.mat','sigma1nodes_nums_uk_near')
load('lambda2nodes_nums_uk_far.mat','lambda2nodes_nums_uk_far')
load('us2nodes_nums_uk_far.mat','us2nodes_nums_uk_far')
load('ws2nodes_nums_uk_far.mat','ws2nodes_nums_uk_far')
load('rhos2nodes_nums_uk_far.mat','rhos2nodes_nums_uk_far')
load('sigma2nodes_nums_uk_far.mat','sigma2nodes_nums_uk_far')
load('spine_nums_uk_far.mat','spine_nums_uk_far')
load('us1nodes_nums_uk_far.mat','us1nodes_nums_uk_far')
load('ws1nodes_nums_uk_far.mat','ws1nodes_nums_uk_far')
load('rhos1nodes_nums_uk_far.mat','rhos1nodes_nums_uk_far')
load('sigma1nodes_nums_uk_far.mat','sigma1nodes_nums_uk_far')
load('c1.mat','c1')
load('c2.mat','c2')
load('a1.mat')
load('o2.mat')
load('n_spines_pre_start_far.mat','n_spines_pre_start_far')
load('S2_nodes_near.mat')
load('E2_nodes_near.mat')
load('D2_nodes_near.mat')
load('T2_nodes_near.mat')
load('S1_nodes_near.mat')
load('E1_nodes_near.mat')
load('D1_nodes_near.mat')
load('T1_nodes_near.mat')
load('S2_nodes_far.mat')
load('E2_nodes_far.mat')
load('D2_nodes_far.mat')
load('T2_nodes_far.mat')
load('S1_nodes_far.mat')
load('E1_nodes_far.mat')
load('D1_nodes_far.mat')
load('T1_nodes_far.mat')

%master elements properties
load('n_Gaussian_Q.mat')
load('T.mat')
load('W_G.mat')
load('xi_G.mat')
load('eta_G.mat')
load('psi_G.mat')
load('phi_G.mat')
load('n_lGaussian_Q.mat')
load('xi_lG.mat')
load('W_lG.mat')
load('phi1_lG.mat')
load('phi1_xi_lG.mat')
load('phi2_lG.mat')
load('phi2_eta_lG.mat')
load('phi3_lG.mat')
load('phi3_xi_lG.mat')
load('phi4_lG.mat')
load('phi4_xi_lG.mat')
load('phi5_lG.mat')
load('phi5_eta_lG.mat')
load('Tmat1.mat')
load('Tmat2.mat')
load('Tmat3.mat')
load('Tmat4.mat')
load('Tmat5.mat')
load('LE_to_TE_1.mat')
load('LE_to_TE_2.mat')
load('LE_to_TE_3.mat')
load('LE_to_TE_4.mat')
load('LE_to_TE_5.mat')

%initial mesh 
load('spine_lengths_ini.mat');
spine_lengths = spine_lengths_ini;
save('spine_lengths_0.mat','spine_lengths')
clear spine_lengths_ini;
[Nodes_rz,R_spines] ...
            = nodes_relocator_split_v02(spine_lengths, ...
                                    spine_feet_locator, ...
                                    n_spines, ...
                                    n_spines_incr,n_v,alpha_s, ...
                                    n_nodes_const_per_spine, ...
                                    n_el_sing);
Nodes_rz_minus1 = Nodes_rz;
Nodes_rz_minus2 = Nodes_rz/2;
load('pNodes_rz.mat')

%initial contact angle
theta_c = pi;
save('theta_c_0.mat','theta_c')
theta_c = pi*170/180;

%Gravity components
gr = 1;
gz = -1;

u = zeros(n_v,1);
w = zeros(n_v,1);

%initial guess vectors
u_bar = ones(n_v_near,1)+.5*rand(n_v_near,1);
w_bar = ones(n_v_near,1)+.5*rand(n_v_near,1); % -1*(1-exp(-Nodes_rz(1:n_v_near,2)));%
u_far = ones(n_v-n_v_pre_start_far,1)+.5*rand(n_v-n_v_pre_start_far,1);
w_far = ones(n_v-n_v_pre_start_far,1)+.5*rand(n_v-n_v_pre_start_far,1);% -1*(1-exp(-Nodes_rz(n_v_start_far:end,2)));%

u_minus1 = ones(n_v,1)+.5*rand(n_v,1);
u_minus2 = u_minus1/2;
w_minus1 = ones(n_v,1)+.5*rand(n_v,1);% -1*(1-exp(-Nodes_rz(:,2)));%
w_minus2 = w_minus1/2;
u_s = ones(n_spines,1)+.5*rand(n_spines,1);
w_s = ones(n_spines,1)+.5*rand(n_spines,1);
A = 1;

u(1:n_v_near) = u_bar;
w(1:n_v_near) = w_bar;
u(n_v_start_far:end) = u_far;
w(n_v_start_far:end) = w_far;
save(['u_',num2str(0),'.mat'],'u')%this should actually store u_minus1
save(['w_',num2str(0),'.mat'],'w')%this should actually store w_minus1
%But it's all the same here


theta_a = pi/2;
save('theta_a.mat','theta_a')
p = ones(n_p,1)+.5*rand(n_p,1);

us1 = ones(n_spines,1)+.5*rand(n_spines,1);
ws1 = ones(n_spines,1)+.5*rand(n_spines,1);
rhos1 = Dg*ones(n_spines,1)+.5*rand(n_spines,1);
save('rhos1_0.mat','rhos1')
rhos1_minus1 = Dg*ones(n_spines,1)+.5*rand(n_spines,1);
rhos1_minus2 = Dg*ones(n_spines,1)/2;
sigma1 = ones(n_spines,1)+.5*rand(n_spines,1);
save('sigma1_0.mat','sigma1')
pg = ones(n_spines,1)+.5*rand(n_spines,1);
 
lambda2 = ones(n_spines,1)+.5*rand(n_spines,1);
us2 = ones(n_spines,1)+.5*rand(n_spines,1);%zeros(n_spines,1);
ws2 = ones(n_spines,1)+.5*rand(n_spines,1);%zeros(n_spines,1);
sigma2(c2) = sigma1(c1);
sigma2 = sigma2(c2)*ones(n_spines,1)+.5*rand(n_spines,1);
save('sigma2_0.mat','sigma2')
rhos2 = ones(n_spines,1)-sigma2/Cs+.5*rand(n_spines,1);
rhos2_minus1 = rhos2+.5*rand(n_spines,1);
save('rhos2_0.mat','rhos2')
rhos2_minus2 = rhos2_minus1/2;

lambda3 = ones(n_spines_incr,1)+.5*rand(n_spines_incr,1);
gamma3 = ones(n_spines_incr,1)+.5*rand(n_spines_incr,1);%this is assumed identically null

% lambda4 = ones(n_spines_near,1)+.5*rand(n_spines_near,1);
% gamma4 = ones(n_spines_near,1)+.5*rand(n_spines_near,1);

%for plotting
n_smooth = 128;
tvec = -1:2/n_smooth:1;
phi_l = (tvec-1).*tvec/2;
phi_c = (tvec+1).*(1-tvec);
phi_r = (tvec+1).*tvec/2;
 
Vels_near = figure;
quiver(Nodes_rz(1:n_v_near,1), ...
       Nodes_rz(1:n_v_near,2), ...
       u_bar, ...
       w_bar,'color',[0 0 0])
% vector used for the curved sides
hold on
%plotting boundaries
for ii = 1:n1_el_near
    xvec =   Nodes_rz(l_1(ii,1),1)*phi_l ...
           + Nodes_rz(l_1(ii,2),1)*phi_c ...
           + Nodes_rz(l_1(ii,3),1)*phi_r;
    yvec =   Nodes_rz(l_1(ii,1),2)*phi_l ...
           + Nodes_rz(l_1(ii,2),2)*phi_c ...
           + Nodes_rz(l_1(ii,3),2)*phi_r;
    plot(xvec,yvec,'b','LineWidth',2)
end
for ii = 1:n2_el_near
    xvec =  Nodes_rz(l_2(ii,1),1)*phi_l ...
          + Nodes_rz(l_2(ii,2),1)*phi_c ...
          + Nodes_rz(l_2(ii,3),1)*phi_r;
    yvec =  Nodes_rz(l_2(ii,1),2)*phi_l ...
          + Nodes_rz(l_2(ii,2),2)*phi_c ...
          + Nodes_rz(l_2(ii,3),2)*phi_r;
    plot(xvec,yvec,'g','LineWidth',2)
end
for ii = 1:n5_el
    xvec =  Nodes_rz(l_5(ii,1),1)*phi_l ...
          + Nodes_rz(l_5(ii,2),1)*phi_c ...
          + Nodes_rz(l_5(ii,3),1)*phi_r;
    yvec =  Nodes_rz(l_5(ii,1),2)*phi_l ...
          + Nodes_rz(l_5(ii,2),2)*phi_c ...
          + Nodes_rz(l_5(ii,3),2)*phi_r;
    plot(xvec,yvec,'r','LineWidth',2)
end
minx = min(Nodes_rz(1:n_v_near,1));
maxx = max(Nodes_rz(1:n_v_near,1));
wi = maxx-minx;
set(gca,'FontSize',16,'xlim',[minx-wi/10 maxx+wi/10])
axis equal
drawnow
hold off

Vels_far = figure;
quiver(Nodes_rz(n_v_start_far:end,1), ...
       Nodes_rz(n_v_start_far:end,2), ...
       u_far, ...
       w_far,'color',[0 0 0])
hold on
%plotting boundaries
for ii = n1_el_near+1:n1_el
    xvec = Nodes_rz(l_1(ii,1),1)*phi_l ...
           +Nodes_rz(l_1(ii,2),1)*phi_c ...
           +Nodes_rz(l_1(ii,3),1)*phi_r;
    yvec = Nodes_rz(l_1(ii,1),2)*phi_l ...
           +Nodes_rz(l_1(ii,2),2)*phi_c ...
           +Nodes_rz(l_1(ii,3),2)*phi_r;
    plot(xvec,yvec,'b','LineWidth',2)
end
for ii = n2_el_near+1:n2_el
    xvec =  Nodes_rz(l_2(ii,1),1)*phi_l ...
           +Nodes_rz(l_2(ii,2),1)*phi_c ...
           +Nodes_rz(l_2(ii,3),1)*phi_r;
    yvec =  Nodes_rz(l_2(ii,1),2)*phi_l ...
           +Nodes_rz(l_2(ii,2),2)*phi_c ...
           +Nodes_rz(l_2(ii,3),2)*phi_r;
    plot(xvec,yvec,'g','LineWidth',2)
end
for ii = 1:n3_el
    xvec =  Nodes_rz(l_3(ii,1),1)*phi_l ...
           +Nodes_rz(l_3(ii,2),1)*phi_c ...
           +Nodes_rz(l_3(ii,3),1)*phi_r;
    yvec =  Nodes_rz(l_3(ii,1),2)*phi_l ...
           +Nodes_rz(l_3(ii,2),2)*phi_c ...
           +Nodes_rz(l_3(ii,3),2)*phi_r;
    plot(xvec,yvec,'r','LineWidth',2)
end
for ii = 1:n4_el
    xvec =  Nodes_rz(l_4(ii,1),1)*phi_l ...
           +Nodes_rz(l_4(ii,2),1)*phi_c ...
           +Nodes_rz(l_4(ii,3),1)*phi_r;
    yvec =  Nodes_rz(l_4(ii,1),2)*phi_l ...
           +Nodes_rz(l_4(ii,2),2)*phi_c ...
           +Nodes_rz(l_4(ii,3),2)*phi_r;
    plot(xvec,yvec,'r','LineWidth',2)
end
set(gca,'FontSize',16,'xlim', ...
    [0 1.1*max(Nodes_rz(n_v_start_far:end,1))])
axis equal                   
drawnow
hold off


%Finding the non-singular hat functions in the singular element
psi_star_G = zeros(3,n_Gaussian_Q);
for pp = 1:n_Gaussian_Q
    psi_star_G(1,pp) = (1+eta_G(pp))/2;
end
for pp = 1:n_Gaussian_Q
    psi_star_G(3,pp) = (1+xi_G(pp))/2;
end

%Derivatives with respect to xi, used to find the tangent at the joint
phi1_xi = zeros(3,2);
xi(1) = 1;
xi(2) = -1;
for pp = 1:2
    phi1_xi(1,pp) = xi(pp)-.5;
    phi1_xi(2,pp) = -2*xi(pp);
    phi1_xi(3,pp) = xi(pp)+.5;
end

%Zeroing vectors of residuals which are not computed additively
Cu = zeros(n_v_sep,1);
Cw = zeros(n_v_sep,1);
Cp = 0;

%creating variables to store data for eigen-solution and singular element
r_pp = 0;
z_pp = 0;
lnR_pp = 0;
psi_star_G(2,pp) = 0;
theta_pol = 0;
phi_pp = 0;
theta_pp = 0;
c_theta_pp = 0;
s_theta_pp =  0;
rho_l_minus2_pp = 0;
rho_l_minus4_pp = 0;
rho_l_minus6_pp = 0;
u_check = zeros(1,n_Gaussian_Q);
w_check = zeros(1,n_Gaussian_Q);
dr_u_check = zeros(1,n_Gaussian_Q);
dz_u_check = zeros(1,n_Gaussian_Q);
dlambda_eig_u_check = zeros(1,n_Gaussian_Q);
dr_w_check = zeros(1,n_Gaussian_Q);
dz_w_check = zeros(1,n_Gaussian_Q);
dlambda_eig_w_check = zeros(1,n_Gaussian_Q);
drr_u_check = zeros(1,n_Gaussian_Q);
drz_u_check = zeros(1,n_Gaussian_Q);
dzz_u_check = zeros(1,n_Gaussian_Q);
drlambda_eig_u_check = zeros(1,n_Gaussian_Q);
dzlambda_eig_u_check = zeros(1,n_Gaussian_Q);
drr_w_check = zeros(1,n_Gaussian_Q);
drz_w_check = zeros(1,n_Gaussian_Q);
dzz_w_check = zeros(1,n_Gaussian_Q);
drlambda_eig_w_check = zeros(1,n_Gaussian_Q);
dzlambda_eig_w_check = zeros(1,n_Gaussian_Q);

%Zeroing variables used in triangle integration
r_e = zeros(6,1);
z_e = zeros(6,1);
det_Je = zeros(1,n_Gaussian_Q);

%Zeroing variables used in line integration
r_le = zeros(3,1);
z_le = zeros(3,1);
r_prime_lGaussian = zeros(1,n_lGaussian_Q);
z_prime_lGaussian = zeros(1,n_lGaussian_Q);
det_Jle = zeros(1,n_lGaussian_Q);

%Measured contact angle
r_le = Nodes_rz(l_1(1,:),1);
z_le = Nodes_rz(l_1(1,:),2);
min_r_le = min(r_le);
min_z_le = min(z_le);
tan1_r = (phi1_xi(:,2)')*(r_le-min_r_le);
tan1_z = (phi1_xi(:,2)')*(z_le-min_z_le);
theta_m = atan2(tan1_z,-tan1_r);

%Zeroing variables used in the Jacobian of triangle elements

%Zeroing variables used in the Jacobian of line-elements

length_of_var = 1;
pert = .000001;

if theta_m > change
    for count = 1:length_of_var
        disp(count/length_of_var)

        %Forward perturbation    
        aux_store = theta_c;
        theta_c = theta_c + pert;
        
        %%%%%%%%%%%%%%%%%%%%%%%%
        R = Res_finder_BDF2_A_v42(n_v_near,n_p_near,n_spines_near, ...
                         n_v_far,n_p_far,n_spines_far, ...
                         theta_c, ...
                         u_bar,w_bar,p, ...
                         lambda2,us2,ws2,rhos2,sigma2, ...
                         us1,ws1,rhos1,sigma1, ...
                         n_v_pre_start_far, ...
                         u_far,w_far, ...
                         n_p_sep, ...
                         A,l,Nodes_rz,n_Gaussian_Q,phi_G, ...
                         xi_G,eta_G,T,W_G,gr,gz,Re,delta_t,St, ...
                         Nodes_rz_minus1,Nodes_rz_minus2, ...
                         u_minus1,u_minus2,w_minus1,w_minus2, ...
                         lp,psi_G,psi_star_G, ...
                         n_el_near,n1_el_near,l_1,l1_1, ...
                         n_lGaussian_Q, W_lG,...
                         phi1_xi_lG,phi1_lG,alpha_1, ...
                         Lg,Dg,Ca,Eg,Bg,Tg,Cg, ...
                         pg,rhos1_minus1,rhos1_minus2, ...
                         contact_line,c1,c2, ...
                         phi1_xi,n_v_sep, ...
                         n2_el_near,l_2,l2_2, ...
                         phi2_eta_lG,phi2_lG,alpha_2, ...
                         Be,Ls,Ds,Es,Ts,Cs, ...
                         u_s,w_s, ...
                         rhos2_minus1,rhos2_minus2, ...
                         n4_el,l_4,l4_4, ...
                         phi4_xi_lG,phi4_lG,alpha_4, ...
                         n_el,n_p_pre_start_far,n1_el,n2_el,n3_el, ...
                         n_spines_pre_start_far,apex,n_spines, ...
                         theta_a, ...
                         l_3,phi3_xi_lG,phi3_lG,alpha_3, ...
                         alpha_5,So, ...
                         n_Mr_near,n_Mz_near,n_C_near, ...
                         n_S2_near,n_I_near,n_E2_near, ...
                         n_D2_near,n_T2_near, ...
                         n_S1_near,n_K_near,n_E1_near, ...
                         n_D1_near,n_T1_near, ...
                         n_Mr_far,n_Mz_far,n_C_far, ...
                         n_S2_far,n_I_far,n_E2_far, ...
                         n_D2_far,n_T2_far, ...
                         n_S1_far,n_K_far,n_E1_far, ...
                         n_D1_far,n_T1_far, ...
                         Mr_nodes_near,Mz_nodes_near, ...
                         C_nodes_near, ...
                         S2_nodes_near,I_nodes_near, ...
                         E2_nodes_near, ...
                         D2_nodes_near,T2_nodes_near, ...
                         S1_nodes_near,K_nodes_near, ...
                         E1_nodes_near, ...
                         D1_nodes_near,T1_nodes_near, ...
                         Mr_nodes_far,Mz_nodes_far, ...
                         C_nodes_far, ...
                         S2_nodes_far,I_nodes_far, ...
                         E2_nodes_far, ...
                         D2_nodes_far,T2_nodes_far, ...
                         S1_nodes_far,K_nodes_far, ...
                         E1_nodes_far, ...
                         D1_nodes_far,T1_nodes_far, ...
                         Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                         LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                         LE_to_TE_4,LE_to_TE_5, ...
                         n5_el,l_5,phi5_lG,phi5_eta_lG, ...
                         a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                         n_el_sing,press_lim_node_solid, ...
                         press_lim_node_gas);

        R_forw(:,count) = R;%#ok

        theta_c = aux_store;
        
        %Backward perturbation
        aux_store = theta_c;
        theta_c = theta_c - pert;
        
        R = Res_finder_BDF2_A_v42(n_v_near,n_p_near,n_spines_near, ...
                         n_v_far,n_p_far,n_spines_far, ...
                         theta_c, ...
                         u_bar,w_bar,p, ...
                         lambda2,us2,ws2,rhos2,sigma2, ...
                         us1,ws1,rhos1,sigma1, ...
                         n_v_pre_start_far, ...
                         u_far,w_far, ...
                         n_p_sep, ...
                         A,l,Nodes_rz,n_Gaussian_Q,phi_G, ...
                         xi_G,eta_G,T,W_G,gr,gz,Re,delta_t,St, ...
                         Nodes_rz_minus1,Nodes_rz_minus2, ...
                         u_minus1,u_minus2,w_minus1,w_minus2, ...
                         lp,psi_G,psi_star_G, ...
                         n_el_near,n1_el_near,l_1,l1_1, ...
                         n_lGaussian_Q, W_lG,...
                         phi1_xi_lG,phi1_lG,alpha_1, ...
                         Lg,Dg,Ca,Eg,Bg,Tg,Cg, ...
                         pg,rhos1_minus1,rhos1_minus2, ...
                         contact_line,c1,c2, ...
                         phi1_xi,n_v_sep, ...
                         n2_el_near,l_2,l2_2, ...
                         phi2_eta_lG,phi2_lG,alpha_2, ...
                         Be,Ls,Ds,Es,Ts,Cs, ...
                         u_s,w_s, ...
                         rhos2_minus1,rhos2_minus2, ...
                         n4_el,l_4,l4_4, ...
                         phi4_xi_lG,phi4_lG,alpha_4, ...
                         n_el,n_p_pre_start_far,n1_el,n2_el,n3_el, ...
                         n_spines_pre_start_far,apex,n_spines, ...
                         theta_a, ...
                         l_3,phi3_xi_lG,phi3_lG,alpha_3, ...
                         alpha_5,So, ...
                         n_Mr_near,n_Mz_near,n_C_near, ...
                         n_S2_near,n_I_near,n_E2_near, ...
                         n_D2_near,n_T2_near, ...
                         n_S1_near,n_K_near,n_E1_near, ...
                         n_D1_near,n_T1_near, ...
                         n_Mr_far,n_Mz_far,n_C_far, ...
                         n_S2_far,n_I_far,n_E2_far, ...
                         n_D2_far,n_T2_far, ...
                         n_S1_far,n_K_far,n_E1_far, ...
                         n_D1_far,n_T1_far, ...
                         Mr_nodes_near,Mz_nodes_near, ...
                         C_nodes_near, ...
                         S2_nodes_near,I_nodes_near, ...
                         E2_nodes_near, ...
                         D2_nodes_near,T2_nodes_near, ...
                         S1_nodes_near,K_nodes_near, ...
                         E1_nodes_near, ...
                         D1_nodes_near,T1_nodes_near, ...
                         Mr_nodes_far,Mz_nodes_far, ...
                         C_nodes_far, ...
                         S2_nodes_far,I_nodes_far, ...
                         E2_nodes_far, ...
                         D2_nodes_far,T2_nodes_far, ...
                         S1_nodes_far,K_nodes_far, ...
                         E1_nodes_far, ...
                         D1_nodes_far,T1_nodes_far, ...
                         Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                         LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                         LE_to_TE_4,LE_to_TE_5, ...
                         n5_el,l_5,phi5_lG,phi5_eta_lG, ...
                         a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                         n_el_sing,press_lim_node_solid, ...
                         press_lim_node_gas);

        R_back(:,count) = R;%#ok

        theta_c = aux_store; 
    end
else
    if A ~= 0
        lambda_eig = pi/theta_m;
        for cc = 2:n_v_near
            r_pp = Nodes_rz(cc,1)-Nodes_rz(1,1);
            z_pp = Nodes_rz(cc,2)-Nodes_rz(1,2);
            theta_pol = theta_polar(r_pp,z_pp);
            phi_pp = pi - theta_c - theta_pol;
            theta_pp = lambda_eig*phi_pp;
            c_theta_pp = cos(theta_pp);
            s_theta_pp = sin(theta_pp);
            rho_l_minus2_pp = (r_pp^2+z_pp^2)^((lambda_eig-2)/2);
            u_check_pp = check_u_of_rz(r_pp,z_pp,lambda_eig, ...
                                       rho_l_minus2_pp,c_theta_pp, ...
                                       s_theta_pp);
            w_check_pp = check_w_of_rz(r_pp,z_pp,lambda_eig, ...
                                       rho_l_minus2_pp,c_theta_pp, ...
                                       s_theta_pp);
            u_bar(cc) = u_bar(cc) + A*u_check_pp;
            w_bar(cc) = w_bar(cc) + A*w_check_pp;
        end
    end
    A = 0;
    for count = 1:length_of_var
        disp(count/length_of_var)

        %Forward perturbation    
        aux_store = theta_c;
        theta_c = theta_c + pert;

        R = Res_finder_BDF2_noA_v42(n_v_near,n_p_near,n_spines_near, ...
                         n_v_far,n_p_far,n_spines_far, ...
                         theta_c, ...
                         u_bar,w_bar,p, ...
                         lambda2,us2,ws2,rhos2,sigma2, ...
                         us1,ws1,rhos1,sigma1, ...
                         n_v_pre_start_far, ...
                         u_far,w_far, ...
                         n_p_sep, ...
                         l,Nodes_rz,n_Gaussian_Q,phi_G, ...
                         xi_G,eta_G,T,W_G,gr,gz,Re,delta_t,St, ...
                         Nodes_rz_minus1,Nodes_rz_minus2, ...
                         u_minus1,u_minus2,w_minus1,w_minus2, ...
                         lp,psi_G,psi_star_G, ...
                         n_el_near,n1_el_near,l_1,l1_1, ...
                         n_lGaussian_Q, W_lG,...
                         phi1_xi_lG,phi1_lG,alpha_1, ...
                         Lg,Dg,Ca,Eg,Bg,Tg,Cg, ...
                         pg,rhos1_minus1,rhos1_minus2, ...
                         contact_line,c1,c2, ...
                         n_v_sep, ...
                         n2_el_near,l_2,l2_2, ...
                         phi2_eta_lG,phi2_lG,alpha_2, ...
                         Be,Ls,Ds,Es,Ts,Cs, ...
                         u_s,w_s, ...
                         rhos2_minus1,rhos2_minus2, ...
                         n4_el,l_4,l4_4, ...
                         phi4_xi_lG,phi4_lG,alpha_4, ...
                         n_el,n_p_pre_start_far,n1_el,n2_el,n3_el, ...
                         n_spines_pre_start_far,apex,n_spines, ...
                         theta_a, ...
                         l_3,phi3_xi_lG,phi3_lG,alpha_3, ...
                         alpha_5,So, ...
                         n_Mr_near,n_Mz_near,n_C_near, ...
                         n_S2_near,n_I_near,n_E2_near, ...
                         n_D2_near,n_T2_near, ...
                         n_S1_near,n_K_near,n_E1_near, ...
                         n_D1_near,n_T1_near, ...
                         n_Mr_far,n_Mz_far,n_C_far, ...
                         n_S2_far,n_I_far,n_E2_far, ...
                         n_D2_far,n_T2_far, ...
                         n_S1_far,n_K_far,n_E1_far, ...
                         n_D1_far,n_T1_far, ...
                         Mr_nodes_near,Mz_nodes_near, ...
                         C_nodes_near, ...
                         S2_nodes_near,I_nodes_near, ...
                         E2_nodes_near, ...
                         D2_nodes_near,T2_nodes_near, ...
                         S1_nodes_near,K_nodes_near, ...
                         E1_nodes_near, ...
                         D1_nodes_near,T1_nodes_near, ...
                         Mr_nodes_far,Mz_nodes_far, ...
                         C_nodes_far, ...
                         S2_nodes_far,I_nodes_far, ...
                         E2_nodes_far, ...
                         D2_nodes_far,T2_nodes_far, ...
                         S1_nodes_far,K_nodes_far, ...
                         E1_nodes_far, ...
                         D1_nodes_far,T1_nodes_far, ...
                         Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                         LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                         LE_to_TE_4,LE_to_TE_5, ...
                         n5_el,l_5,phi5_lG,phi5_eta_lG, ...
                         a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                         n_el_sing);

        R_forw(:,count) = R;%#ok

        theta_c = aux_store;
        
        %Backward perturbation
        aux_store = theta_c;
        theta_c = theta_c - pert;

        R = Res_finder_BDF2_noA_v42(n_v_near,n_p_near,n_spines_near, ...
                         n_v_far,n_p_far,n_spines_far, ...
                         theta_c, ...
                         u_bar,w_bar,p, ...
                         lambda2,us2,ws2,rhos2,sigma2, ...
                         us1,ws1,rhos1,sigma1, ...
                         n_v_pre_start_far, ...
                         u_far,w_far, ...
                         n_p_sep, ...
                         l,Nodes_rz,n_Gaussian_Q,phi_G, ...
                         xi_G,eta_G,T,W_G,gr,gz,Re,delta_t,St, ...
                         Nodes_rz_minus1,Nodes_rz_minus2, ...
                         u_minus1,u_minus2,w_minus1,w_minus2, ...
                         lp,psi_G,psi_star_G, ...
                         n_el_near,n1_el_near,l_1,l1_1, ...
                         n_lGaussian_Q, W_lG,...
                         phi1_xi_lG,phi1_lG,alpha_1, ...
                         Lg,Dg,Ca,Eg,Bg,Tg,Cg, ...
                         pg,rhos1_minus1,rhos1_minus2, ...
                         contact_line,c1,c2, ...
                         n_v_sep, ...
                         n2_el_near,l_2,l2_2, ...
                         phi2_eta_lG,phi2_lG,alpha_2, ...
                         Be,Ls,Ds,Es,Ts,Cs, ...
                         u_s,w_s, ...
                         rhos2_minus1,rhos2_minus2, ...
                         n4_el,l_4,l4_4, ...
                         phi4_xi_lG,phi4_lG,alpha_4, ...
                         n_el,n_p_pre_start_far,n1_el,n2_el,n3_el, ...
                         n_spines_pre_start_far,apex,n_spines, ...
                         theta_a, ...
                         l_3,phi3_xi_lG,phi3_lG,alpha_3, ...
                         alpha_5,So, ...
                         n_Mr_near,n_Mz_near,n_C_near, ...
                         n_S2_near,n_I_near,n_E2_near, ...
                         n_D2_near,n_T2_near, ...
                         n_S1_near,n_K_near,n_E1_near, ...
                         n_D1_near,n_T1_near, ...
                         n_Mr_far,n_Mz_far,n_C_far, ...
                         n_S2_far,n_I_far,n_E2_far, ...
                         n_D2_far,n_T2_far, ...
                         n_S1_far,n_K_far,n_E1_far, ...
                         n_D1_far,n_T1_far, ...
                         Mr_nodes_near,Mz_nodes_near, ...
                         C_nodes_near, ...
                         S2_nodes_near,I_nodes_near, ...
                         E2_nodes_near, ...
                         D2_nodes_near,T2_nodes_near, ...
                         S1_nodes_near,K_nodes_near, ...
                         E1_nodes_near, ...
                         D1_nodes_near,T1_nodes_near, ...
                         Mr_nodes_far,Mz_nodes_far, ...
                         C_nodes_far, ...
                         S2_nodes_far,I_nodes_far, ...
                         E2_nodes_far, ...
                         D2_nodes_far,T2_nodes_far, ...
                         S1_nodes_far,K_nodes_far, ...
                         E1_nodes_far, ...
                         D1_nodes_far,T1_nodes_far, ...
                         Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                         LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                         LE_to_TE_4,LE_to_TE_5, ...
                         n5_el,l_5,phi5_lG,phi5_eta_lG, ...
                         a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                         n_el_sing);

        R_back(:,count) = R;%#ok

        theta_c = aux_store; 
    end
end

diff_num = (R_forw-R_back)/(2*pert);

if theta_m > change
    JR = Jacobian_finder_BDF2_A_v42(n_v_near,n_p_near, ...
                       n_spines_near, ...
                       n_spines_far, ...
                       n_lambda2_uk_near,n_sigma2_uk_near, ...
                       n_v_sep,n_v_far,n_p_far, ...
                       theta_c,del_h, ...
                       spine_lengths,n_spines, ...
                       spine_feet_locator,spine_feet_nodes, ...
                       n_spines_incr,n_v, ...
                       spine_tip_nodes,alpha_s,R_spines, ...
                       l,Nodes_rz,S,el_s_loc_nodes, ...
                       n_Gaussian_Q,T,xi_G,eta_G, ...
                       phi_G,psi_G,W_G, ...
                       gr,gz, ...
                       Re,St,Ca, ...
                       A,delta_t, ...
                       w_bar,u_bar, ...
                       Nodes_rz_minus1,Nodes_rz_minus2, ...
                       u_minus1,u_minus2,w_minus1,w_minus2, ...
                       lp,p,psi_star_G, ...
                       n_el_near,c1,contact_line, ...
                       sigma1,us1,ws1,rhos1, ...
                       l_1,l1_1,S_1,el1_s_loc_nodes,alpha_1, ...
                       Tg,Lg,Dg,Eg,Bg, ...
                       n_lGaussian_Q,phi1_lG,phi1_xi_lG,W_lG, ...
                       pg,rhos1_minus1,rhos1_minus2, ...
                       n1_el_near,c2, ...
                       phi1_xi, ...
                       Ts,Be,Ls,Ds,Es, ...
                       us2,ws2,rhos2, ...
                       l_2,l2_2,S_2,el2_s_loc_nodes, ...
                       phi2_lG,phi2_eta_lG,alpha_2, ...
                       u_s,w_s,lambda2, ...
                       rhos2_minus1,rhos2_minus2, ...
                       n2_el_near, ...
                       n4_el,l_4,l4_4,S_4,el4_s_loc_nodes, ...
                       phi4_lG,phi4_xi_lG,alpha_4, ...
                       n_v_pre_start_far,n_el, ...
                       u_far,w_far,n_p_pre_start_far, ...
                       theta_a,n1_el, ...
                       n_spines_pre_start_far, ...
                       n2_el,n3_el,l_3, ...
                       S_3,el3_s_loc_nodes, ...
                       phi3_xi_lG,phi3_lG,alpha_3, ...
                       alpha_5, ...
                       n_Mr_near,n_Mz_near,n_C_near, ...
                       n_S2_near,n_I_near,n_E2_near, ...
                       n_D2_near,n_T2_near, ...
                       n_S1_near,n_K_near,n_E1_near, ...
                       n_D1_near,n_T1_near, ...
                       n_Mr_far,n_Mz_far,n_C_far, ...
                       n_S2_far,n_I_far,n_E2_far, ...
                       n_D2_far,n_T2_far, ...
                       n_S1_far,n_K_far,n_E1_far, ...
                       n_D1_far,n_T1_far, ...
                       Mr_nodes_near,Mz_nodes_near,C_nodes_near, ...
                       S2_nodes_near, ...
                       I_nodes_near, ...
                       S1_nodes_near, ...
                       Mr_nodes_far,Mz_nodes_far,C_nodes_far, ...
                       S2_nodes_far, ...
                       S1_nodes_far, ...
                       n_p_sep, ...
                       n_u_uk_near,n_w_uk_near,n_p_uk_near, ...
                       n_us2_uk_near,n_ws2_uk_near,n_rhos2_uk_near, ...
                       n_us1_uk_near,n_ws1_uk_near,n_rhos1_uk_near, ...
                       n_u_uk_far,n_w_uk_far,n_p_uk_far, ...
                       n_us2_uk_far,n_ws2_uk_far,n_rhos2_uk_far, ...
                       n_us1_uk_far,n_ws1_uk_far,n_rhos1_uk_far, ...
                       n_sigma1_uk_far, ...
                       unodes_nums_uk_near,wnodes_nums_uk_near, ...
                       pnodes_nums_uk_near, ...
                       lambda2nodes_nums_uk_near, ...
                       us2nodes_nums_uk_near, ...
                       ws2nodes_nums_uk_near, ...    
                       sigma2nodes_nums_uk_near, ...
                       sigma2nodes_nums_uk_far, ...
                       n_sigma1_uk_near, ...
                       n_lambda2_uk_far,n_sigma2_uk_far, ...
                       unodes_nums_uk_far,wnodes_nums_uk_far, ...
                       Cs,Cg, ...
                       pnodes_nums_uk_far, ...
                       lambda2nodes_nums_uk_far, ...
                       us2nodes_nums_uk_far, ...
                       ws2nodes_nums_uk_far, ...
                       us1nodes_nums_uk_far, ...
                       ws1nodes_nums_uk_far, ...
                       sigma1nodes_nums_uk_far, ...
                       sigma1nodes_nums_uk_near, ...
                       rhos1nodes_nums_uk_near, ...
                       rhos1nodes_nums_uk_far, ...
                       rhos2nodes_nums_uk_near, ...
                       rhos2nodes_nums_uk_far, ...
                       Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                       LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                       LE_to_TE_4,LE_to_TE_5, ...
                       n5_el,l_5,phi5_lG,phi5_eta_lG,S_5, ...
                       el5_s_loc_nodes, ...
                       us1nodes_nums_uk_near, ...
                       ws1nodes_nums_uk_near, ...
                       K_nodes_near, ...
                       K_nodes_far, ...
                       E1_nodes_near, ...
                       E1_nodes_far, ...
                       I_nodes_far, ...
                       E2_nodes_far, ...
                       E2_nodes_near, ...
                       D2_nodes_near, ...
                       D1_nodes_near,D2_nodes_far,D1_nodes_far, ...
                       a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                       n_nodes_const_per_spine,n_el_sing,...
                       press_lim_node_solid, ...
                       press_lim_node_gas);
else
    JR = Jacobian_finder_BDF2_noA_v42(n_v_near,n_p_near, ...
                           n_spines_near, ...
                           n_spines_far, ...
                           n_lambda2_uk_near,n_sigma2_uk_near, ...
                           n_v_sep,n_v_far,n_p_far, ...
                           theta_c,del_h, ...
                           spine_lengths,n_spines, ...
                           spine_feet_locator,spine_feet_nodes, ...
                           n_spines_incr,n_v, ...
                           spine_tip_nodes,alpha_s,R_spines, ...
                           l,Nodes_rz,S,el_s_loc_nodes, ...
                           n_Gaussian_Q,T,xi_G,eta_G, ...
                           phi_G,psi_G,W_G, ...
                           gr,gz, ...
                           Re,St,Ca, ...
                           delta_t, ...
                           w_bar,u_bar, ...
                           Nodes_rz_minus1,Nodes_rz_minus2, ...
                           u_minus1,u_minus2,w_minus1,w_minus2, ...
                           lp,p,psi_star_G, ...
                           n_el_near,c1,contact_line, ...
                           sigma1,us1,ws1,rhos1, ...
                           l_1,l1_1,S_1,el1_s_loc_nodes,alpha_1, ...
                           Tg,Lg,Dg,Eg,Bg, ...
                           n_lGaussian_Q,phi1_lG,phi1_xi_lG,W_lG, ...
                           pg,rhos1_minus1,rhos1_minus2, ...
                           n1_el_near,c2, ...
                           Ts,Be,Ls,Ds,Es, ...
                           us2,ws2,rhos2, ...
                           l_2,l2_2,S_2,el2_s_loc_nodes, ...
                           phi2_lG,phi2_eta_lG,alpha_2, ...
                           u_s,w_s,lambda2, ...
                           rhos2_minus1,rhos2_minus2, ...
                           n2_el_near, ...
                           n4_el,l_4,l4_4,S_4,el4_s_loc_nodes, ...
                           phi4_lG,phi4_xi_lG,alpha_4, ...
                           n_v_pre_start_far,n_el, ...
                           u_far,w_far,n_p_pre_start_far, ...
                           theta_a,n1_el, ...
                           n_spines_pre_start_far, ...
                           n2_el,n3_el,l_3, ...
                           S_3,el3_s_loc_nodes, ...
                           phi3_xi_lG,phi3_lG,alpha_3, ...
                           alpha_5, ...
                           n_Mr_near,n_Mz_near,n_C_near, ...
                           n_S2_near,n_I_near,n_E2_near, ...
                           n_D2_near,n_T2_near, ...
                           n_S1_near,n_K_near,n_E1_near, ...
                           n_D1_near,n_T1_near, ...
                           n_Mr_far,n_Mz_far,n_C_far, ...
                           n_S2_far,n_I_far,n_E2_far, ...
                           n_D2_far,n_T2_far, ...
                           n_S1_far,n_K_far,n_E1_far, ...
                           n_D1_far,n_T1_far, ...
                           Mr_nodes_near,Mz_nodes_near, ...
                           C_nodes_near, ...
                           S2_nodes_near, ...
                           I_nodes_near, ...
                           S1_nodes_near, ...
                           Mr_nodes_far,Mz_nodes_far, ...
                           C_nodes_far, ...
                           S2_nodes_far, ...
                           S1_nodes_far, ...
                           n_p_sep, ...
                           n_u_uk_near,n_w_uk_near, ...
                           n_p_uk_near, ...
                           n_us2_uk_near,n_ws2_uk_near, ...
                           n_rhos2_uk_near, ...
                           n_us1_uk_near,n_ws1_uk_near, ...
                           n_rhos1_uk_near, ...
                           n_u_uk_far,n_w_uk_far,n_p_uk_far, ...
                           n_us2_uk_far,n_ws2_uk_far, ...
                           n_rhos2_uk_far, ...
                           n_us1_uk_far,n_ws1_uk_far, ...
                           n_rhos1_uk_far, ...
                           n_sigma1_uk_far, ...
                           unodes_nums_uk_near,wnodes_nums_uk_near, ...
                           pnodes_nums_uk_near, ...
                           lambda2nodes_nums_uk_near, ...
                           us2nodes_nums_uk_near, ...
                           ws2nodes_nums_uk_near, ...    
                           sigma2nodes_nums_uk_near, ...
                           sigma2nodes_nums_uk_far, ...
                           n_sigma1_uk_near, ...
                           n_lambda2_uk_far,n_sigma2_uk_far, ...
                           unodes_nums_uk_far,wnodes_nums_uk_far, ...
                           Cs,Cg, ...
                           pnodes_nums_uk_far, ...
                           lambda2nodes_nums_uk_far, ...
                           us2nodes_nums_uk_far, ...
                           ws2nodes_nums_uk_far, ...
                           us1nodes_nums_uk_far, ...
                           ws1nodes_nums_uk_far, ...
                           sigma1nodes_nums_uk_far, ...
                           sigma1nodes_nums_uk_near, ...
                           rhos1nodes_nums_uk_near, ...
                           rhos1nodes_nums_uk_far, ...
                           rhos2nodes_nums_uk_near, ...
                           rhos2nodes_nums_uk_far, ...
                           Tmat1,Tmat2,Tmat3,Tmat4,Tmat5, ...
                           LE_to_TE_1,LE_to_TE_2,LE_to_TE_3, ...
                           LE_to_TE_4,LE_to_TE_5, ...
                           n5_el,l_5,phi5_lG,phi5_eta_lG,S_5, ...
                           el5_s_loc_nodes, ...
                           us1nodes_nums_uk_near, ...
                           ws1nodes_nums_uk_near, ...
                           K_nodes_near, ...
                           K_nodes_far, ...
                           E1_nodes_near, ...
                           E1_nodes_far, ...
                           I_nodes_far, ...
                           E2_nodes_far, ...
                           E2_nodes_near, ...
                           D2_nodes_near, ...
                           D1_nodes_near,D2_nodes_far,D1_nodes_far, ...
                           a1,o2,a_n,a_n_minus1,a_n_minus2, ...
                           n_nodes_const_per_spine,n_el_sing);
end



       
%%
%theta_c
aux1 = JR(:,n_u_uk_near+n_w_uk_near+n_p_uk_near ...
            +n_lambda2_uk_near+n_us2_uk_near+n_ws2_uk_near+n_rhos2_uk_near+n_sigma2_uk_near ...
            +n_spines_near+n_us1_uk_near+n_ws1_uk_near+n_rhos1_uk_near+n_sigma1_uk_near ...
            +n_u_uk_far+n_w_uk_far+n_p_uk_far-n_p_sep ...
            +n_lambda2_uk_far-1+n_us2_uk_far-1+n_ws2_uk_far-1+n_rhos2_uk_far-1+n_sigma2_uk_far-1 ...
            +n_spines_far-1+n_us1_uk_far-1+n_ws1_uk_far-1+n_rhos1_uk_far-1+n_sigma1_uk_far-1 ...
            +1);
aux2 = diff_num;
rel_err =   abs(aux1-aux2)./abs(aux1) ...
          + abs(aux1-aux2)./abs(aux2); 
rel_err(isnan(rel_err)) = Inf;
figure
subplot(1,2,1)
plot(rel_err)
title('Relative error in $\partial_{\theta_c}$', ...
      'interpreter','latex','FontSize',16)
subplot(1,2,2)
plot((rel_err>1E-4) ...
     .*abs(aux1-aux2))
title(['Absolute error of $\partial_{\theta_c}$ ', ...
      'where relative error is greater than 1E-4'], ...
      'interpreter','latex','FontSize',16)
  
  
vector_of_eqns = ['End_Mr_bar = ',num2str(n_Mr_near),', ', ...
                  'End_Mz_bar = ',num2str(n_Mr_near+n_Mz_near),', ', ...
                  'End_C_near = ',num2str(n_Mr_near+n_Mz_near+n_C_near),', ', ...
                  'End_S2_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near)),', ', ...
                  'End_I_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near)),', ', ...
                  'End_E2_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near)),', ', ...
                  'End_D2_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near)),', ', ...
                  'End_T2_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near)),', ', ...
                  'End_S1_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near)),', ', ...
                  'End_K_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near)),', ', ...
                  'End_E1_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near)),', ', ...
                  'End_D1_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near)),', ', ...
                  'End_T1_near = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near)),', ', ...
                  'End_Cu = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +n_v_sep)),', ', ...
                  'End_Cw = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep)),', ', ...
                  'End_Mr_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep)),', ', ...
                  'End_Mz_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep)),', ', ...
                  'End_C_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep)),', ', ...
                  'End_S2_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1)),', ', ...
                  'End_I_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1)),', ', ...
                  'End_E2_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1)),', ', ...
                  'End_D2_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1)),', ', ...
                  'End_T2_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1)),', ', ...
                  'End_S1_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1)),', ', ...
                  'End_K_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1)),', ', ...
                  'End_E1_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1+n_E1_far-1)),', ', ...
                  'End_D1_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1+n_E1_far-1+n_D1_far-1)),', ', ...
                  'End_T1_far = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1+n_E1_far-1+n_D1_far-1+n_T1_far-1)),', ', ...
                  'End_Y = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1+n_E1_far-1+n_D1_far-1+n_T1_far-1 ...
                   +2)),', ', ...
                   'End_Cp = ',num2str((n_Mr_near+n_Mz_near+n_C_near ...
                   +n_S2_near+n_I_near+n_E2_near+n_D2_near+n_T2_near ...
                   +n_S1_near+n_K_near+n_E1_near+n_D1_near+n_T1_near ...
                   +2*n_v_sep ...
                   +n_Mr_far-n_v_sep+n_Mz_far-n_v_sep+n_C_far-n_p_sep ...
                   +n_S2_far-1+n_K_far-1+n_E2_far-1+n_D2_far-1+n_T2_far-1 ...
                   +n_S1_far-1+n_K_far-1+n_E1_far-1+n_D1_far-1+n_T1_far-1 ...
                   +3))]%#ok
              
              
              
              
              
              
              
              
              
              
              
              